// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6BhCEfiUA64TDFih_uXGYp_fM74fZ0cI',
    appId: '1:446389456516:web:860fda62202d1d2b707cd1',
    messagingSenderId: '446389456516',
    projectId: 'narad-5920c',
    authDomain: 'narad-5920c.firebaseapp.com',
    storageBucket: 'narad-5920c.appspot.com',
    measurementId: 'G-WBYLG05NGP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX8ke-FVsO2qgz8ahVm6LiEBc5F838WdE',
    appId: '1:446389456516:android:5ec200025a0f6575707cd1',
    messagingSenderId: '446389456516',
    projectId: 'narad-5920c',
    storageBucket: 'narad-5920c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGKQjryAlncO9QvbnmGkbR4KGhMJG4kqM',
    appId: '1:446389456516:ios:80fba164ee5653f8707cd1',
    messagingSenderId: '446389456516',
    projectId: 'narad-5920c',
    storageBucket: 'narad-5920c.appspot.com',
    androidClientId: '446389456516-imtgntk8luernbrtjtll6htvotelcj5v.apps.googleusercontent.com',
    iosBundleId: 'com.app.advanceflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGKQjryAlncO9QvbnmGkbR4KGhMJG4kqM',
    appId: '1:446389456516:ios:f6e626bd129535be707cd1',
    messagingSenderId: '446389456516',
    projectId: 'narad-5920c',
    storageBucket: 'narad-5920c.appspot.com',
    androidClientId: '446389456516-imtgntk8luernbrtjtll6htvotelcj5v.apps.googleusercontent.com',
    iosBundleId: 'com.app.advanceflutter.RunnerTests',
  );
}
